#!/usr/bin/env python3
#
# pdf-compress - ghostrscipt wrapper for PDF compression
# 2026-04 Boruch-Baum
#
# Adapted from: https://github.com/hkdb/cpdf    <hkdb@3df.io>

import shutil          # for which
from sys import version_info, argv, exit
from os  import path   # for basename, isfile, getsize
from re  import search # for search, search.group
from subprocess import Popen, PIPE, STDOUT

VERSION = "v2026.04.14"

MIN_PYTHON = (3, 10)
# Calculated using 'vermin'
# * v3.10 :: match
# * v3.8  :: named expressions (walrus operator)
# * v3.6  :: f-strings

def help_msg():
  print( f"Usage: {path.basename( __file__ )} type input-file output-file" )
  print( """
Compress a pdf file, using ghostscript\n
types:\033[1;37m \tscreen \033[0m   - lowest-resolution
\033[1;37m \tebook    \033[0m - medium-resolution
\033[1;37m \tprinter  \033[0m - print optimized
\033[1;37m \tprepress \033[0m - prepress optimized
\033[1;37m \tdefault  \033[0m - least compressed
""")


def err_print(msg):
  print(f'{path.basename( __file__ )}: \033[91mERROR: \033[0m {msg}')


def warn_print(msg):
  return f'\033[1;36mWARNING: \033[0m {msg}'


def yes_no(prompt):
  while True:
    answer = input( f'{prompt} (y/n): ' ).strip().lower()
    if answer in ("y", "yes"):
      return True
    if answer in ("n", "no"):
      return False
    print("Please enter yes or no.")


def arg_parse():
  match len(argv)-1:
    case 1:
      if str(argv[1]) == "version":
        print( f'{path.basename( __file__ )} {VERSION}')
      else:
        help_msg()
      exit()
    case 3:
      pass
    case _:
      help_msg()
      exit()
  if str(argv[1]) not in ("screen", "ebook", "printer", "prepress", "default"):
    err_print(f"Incorrect compression type: {argv[1]}")
    help_msg()
    exit()
  if not str(argv[2]).endswith(".pdf"):
    err_print("Input filename does not end with a \".pdf\" extension.")
    exit()
  elif str(argv[2]) == str(argv[3]):
    err_print("Input and output filenames are identical.")
    exit()


def invalid_chars(searchText, printText):
  if found := search('[|;`><{}#*]', searchText):
    err_print( f'{printText} contains invalid character {found.group()}"' )
    exit()


def sanity_checks(inFile, outFile):
  exist = path.isfile(inFile)
  if exist == False:
    err_print( f'{inFile} does not exist.')
    exit()
  invalid_chars(inFile,  "Input filename")
  invalid_chars(outFile, "Output filename")
  if path.isfile(outFile):
    if not yes_no( warn_print( f'Output file "{outFile}" exists. Overwrite?') ):
      exit()
  if not outFile.endswith(".pdf"):
    if not yes_no( warn_print( f'Output file "{outFile}" ' +
                               f'does not end with ".pdf". Continue?') ):
      exit()


def main():
  if version_info < MIN_PYTHON:
    print("Requires Python version >= " + str(MIN_PYTHON[0]) + "." + str(MIN_PYTHON[1]) )
    exit()
  if not shutil.which("gs"):
    err_print( "Ghostscript not installed." )
    exit()
  arg_parse()
  cType   = str(argv[1]) # Compression Type
  inFile  = str(argv[2]) # Input File Name
  outFile = str(argv[3]) # Output File Name
  sanity_checks(inFile, outFile)
  cmmd = [
      'gs',
      '-sDEVICE=pdfwrite',
      '-dCompatibilityLevel=1.6',
      f'-dPDFSETTINGS=/{cType}',
      '-dNOPAUSE',
      '-dQUIET',
      '-dBATCH',
      f'-sOutputFile={outFile}',
      inFile
  ]
  # Run Ghostscript Command
  process = Popen(cmmd, stdout=PIPE, stderr=STDOUT)
  # Progress & Details
  initial_size = path.getsize(inFile)
  status = 0
  n = int(initial_size)
  for i in range(n):
    if process.poll() == None:
      if status % 100 == 0:
        print(f"Working... {status}", end="\r", flush=True)
      status += 1
    else:
      break
  process.wait(timeout=2)
  print("\nCompressed!")
  final_size = path.getsize(outFile)
  inSize = str(initial_size / 1000000)
  print(f"Input file:   {initial_size / 1000000:.2f}Mb  {inFile}")
  print(f"Output file:  {final_size / 1000000:.2f}Mb  {outFile}")


if __name__ == "__main__":
    main()
